-- 009: Seed common skills and certifications for Master Lists
-- Run after v56 migration creates the tables.

INSERT IGNORE INTO master_skills (name) VALUES
('Communication'),
('Leadership'),
('Problem Solving'),
('Teamwork'),
('Time Management'),
('Project Management'),
('Critical Thinking'),
('Decision Making'),
('Adaptability'),
('Creativity'),
('Attention to Detail'),
('Organizational Skills'),
('Negotiation'),
('Conflict Resolution'),
('Customer Service'),
('Presentation Skills'),
('Public Speaking'),
('Research'),
('Writing'),
('Data Analysis'),
('Microsoft Excel'),
('Microsoft PowerPoint'),
('Microsoft Word'),
('Microsoft Office'),
('Python'),
('JavaScript'),
('Java'),
('SQL'),
('HTML'),
('CSS'),
('React'),
('Node.js'),
('Agile/Scrum'),
('SAP'),
('AutoCAD'),
('Photoshop'),
('Salesforce'),
('Power BI'),
('Tableau'),
('Digital Marketing'),
('SEO'),
('Graphic Design'),
('Financial Analysis'),
('Accounting'),
('Supply Chain Management'),
('Quality Control'),
('Six Sigma'),
('Risk Management'),
('Strategic Planning'),
('Sales'),
('English'),
('French'),
('German');

INSERT IGNORE INTO master_certifications (name) VALUES
('PMP – Project Management Professional'),
('CFA – Chartered Financial Analyst'),
('CMA – Certified Management Accountant'),
('CPA – Certified Public Accountant'),
('ACCA'),
('SHRM-CP'),
('SHRM-SCP'),
('PHR – Professional in Human Resources'),
('SPHR – Senior Professional in Human Resources'),
('Six Sigma Green Belt'),
('Six Sigma Black Belt'),
('CISSP – Certified Information Systems Security Professional'),
('CISM – Certified Information Security Manager'),
('CEH – Certified Ethical Hacker'),
('CompTIA A+'),
('CompTIA Network+'),
('CompTIA Security+'),
('AWS Certified Solutions Architect'),
('Google Cloud Professional'),
('Microsoft Azure Administrator'),
('MCSE'),
('CCNA'),
('ITIL Foundation'),
('PRINCE2'),
('Certified Scrum Master'),
('SAFe Agilist'),
('Google Analytics Certification'),
('HubSpot Certification'),
('TOEFL'),
('IELTS'),
('CIA – Certified Internal Auditor'),
('CISA – Certified Information Systems Auditor'),
('CRISC – Certified in Risk and Information Systems Control'),
('LEED Green Associate'),
('OSHA 30-Hour Training'),
('ISO 9001 Lead Auditor'),
('Oracle Certified Professional'),
('Microsoft Office Specialist (MOS)');
